version: '3.7'
services: 
    service-one: 
        image: 967rajkumar/mmv2-service-one:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - "8081:8081"
        networks: 
            - service-network
        depends_on : 
            - naming-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka     
      
    naming-server: 
        image: 967rajkumar/mmv2-eureka-server:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports: 
            - "8761:8761"
        networks: 
            - service-network 
networks: 
    service-network: 